# -*- coding: utf-8 -*-
"""дрисня.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pSJ9_hNHAxfdE2XdiKyrcyvlF_KnJDOo
"""

print('Hello, world!')